//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.12 at 12:53:08 PM IDT 
//


package com.example.soap.spring_boot_soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.soap.spring_boot_soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.soap.spring_boot_soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllResponse }
     * 
     */
    public GetAllResponse createGetAllResponse() {
        return new GetAllResponse();
    }

    /**
     * Create an instance of {@link UpdateOrCreateRequest }
     * 
     */
    public UpdateOrCreateRequest createUpdateOrCreateRequest() {
        return new UpdateOrCreateRequest();
    }

    /**
     * Create an instance of {@link Customer }
     * 
     */
    public Customer createCustomer() {
        return new Customer();
    }

    /**
     * Create an instance of {@link GetOrDeleteCustomerIDRequest }
     * 
     */
    public GetOrDeleteCustomerIDRequest createGetOrDeleteCustomerIDRequest() {
        return new GetOrDeleteCustomerIDRequest();
    }

    /**
     * Create an instance of {@link GetAllRequest }
     * 
     */
    public GetAllRequest createGetAllRequest() {
        return new GetAllRequest();
    }

}
