//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.11 at 10:47:56 PM IDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://soap.example.com/spring-boot-soap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.soap.spring_boot_soap;
